package sandbox;

/**
 * Single JVM-wide slot holding the active {@link RuntimeGuard}.
 *
 * <p>{@link RuntimeGuard} is a Spring singleton bean and holds no static state of its own, but
 * {@link InterceptCustomizer}-generated bytecode still needs some static, DI-free way to reach
 * it - compiled code can only carry compile-time constants, never a live object reference.
 * Since there is exactly one guard per JVM (one Spring context, one bean), a single field is
 * enough - no need to key by ClassLoader or anything else.
 *
 * <p>{@link RuntimeGuard} populates this via its {@code @PostConstruct}/{@code @PreDestroy}
 * hooks as Spring creates/destroys the bean. {@link #set} is only ever called from that
 * lifecycle hook (host/framework code); {@link #get} is the only entry point
 * customizer-generated bytecode calls, so nothing a script does can reach {@link #set}.
 */
final class GuardHolder {

    private static volatile RuntimeGuard instance;

    static void set(RuntimeGuard guard) {
        instance = guard;
    }

    /** Clears the slot only if it still holds {@code guard} - avoids one bean's shutdown
     *  wiping out a different, newer bean's registration. */
    static void clear(RuntimeGuard guard) {
        if (instance == guard) {
            instance = null;
        }
    }

    static RuntimeGuard get() {
        RuntimeGuard guard = instance;
        if (guard == null) {
            throw new SecurityException("No RuntimeGuard registered - is the Spring context up?");
        }
        return guard;
    }

    private GuardHolder() {}
}
