package sandbox;

import groovy.lang.Closure;
import groovy.lang.MetaClass;
import groovy.lang.MetaClassImpl;
import groovy.lang.MetaMethod;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import org.apache.commons.lang3.ObjectUtils;
import org.codehaus.groovy.runtime.InvokerHelper;
import org.codehaus.groovy.runtime.MetaClassHelper;

/**
 * Runtime insurance for scripts compiled by {@link InterceptCustomizer}. Framework-agnostic on
 * purpose - it has no Spring annotations of its own. {@link RuntimeGuardConfiguration} builds
 * it as a {@code @Bean} from externalized configuration and wires {@link #registerAsActiveGuard()}/
 * {@link #unregisterAsActiveGuard()} as its init/destroy methods; {@link GuardHolder} is what
 * lets customizer-generated bytecode (which can only bake in compile-time constants, never a
 * live object reference) reach whichever instance that bean-creation produced.
 */
public final class RuntimeGuard {

    /**
     * Class name -> method names a script may call on it. Checked against the class that
     * actually declares the resolved method, not the receiver's static/declared type -
     * otherwise a whitelisted interface could be used to reach an unlisted implementation.
     * An empty method set means every method on that class is allowed; a class missing from
     * the map entirely is not allowed at all. {@code Set}, not {@code List} - every lookup
     * here is a membership check ({@link #isMethodAllowed}), and that's called on every
     * intercepted call a script makes, so it should be O(1) rather than a linear scan.
     * Supplied by the caller (see {@link RuntimeGuardConfiguration} for the Spring-wired
     * default) rather than hardcoded, so different deployments can run different whitelists
     * without touching this class.
     */
    private final Map<String, Set<String>> allowedMethods;

    /**
     * Denied on every receiver, even an allowed one - each is a one-hop escape from the
     * sandbox (reflection, metaclass tampering, or a call the JVM makes outside our control).
     */
    private final Set<String> deniedMethods = new HashSet<>(Arrays.asList(
            "getClass", "getMetaClass", "setMetaClass",
            "getClassLoader", "forName",
            "invokeMethod", "getProperty", "setProperty",
            "wait", "notify", "notifyAll", "finalize"
    ));

    public RuntimeGuard(Map<String, Set<String>> allowedMethods) {
        this.allowedMethods = allowedMethods.entrySet().stream()
                .collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, e -> Set.copyOf(e.getValue())));
    }

    // ------------------------------------------------------------------ methods

    /**
     * @param safe   {@code a?.m()} call
     * @param spread {@code a*.m()} call
     */
    public Object checkedCall(Object receiver, boolean safe, boolean spread,
                               Object methodName, Object[] args) {
        String method = String.valueOf(methodName);
        args = fixNull(args);

        if (safe && Objects.isNull(receiver)) return null;

        if (spread) {
            List<Object> out = new ArrayList<>();
            for (Iterator<?> it = InvokerHelper.asIterator(receiver); it.hasNext(); ) {
                Object o = it.next();
                if (Objects.nonNull(o)) out.add(checkedCall(o, true, false, method, args));
            }
            return out;
        }

        if (Objects.isNull(receiver)) {
            // Groovy treats this as NullObject; nothing dangerous can be reached this way.
            return InvokerHelper.invokeMethod(null, method, args);
        }

        Class<?>[] argTypes = MetaClassHelper.convertToTypeArray(args);

        // "Foo.bar()" compiles to a plain call with a Class receiver. Distinguish a static
        // method on Foo from an instance method of java.lang.Class itself.
        if (receiver instanceof Class) {
            MetaClass mc = InvokerHelper.getMetaClass((Class<?>) receiver);
            if (mc instanceof MetaClassImpl) {
                MetaMethod sm = ((MetaClassImpl) mc).retrieveStaticMethod(method, args);
                if (Objects.nonNull(sm) && sm.isStatic()) {
                    Class<?> declaring = sm.getDeclaringClass().getTheClass();
                    check(declaring, method, argTypes);
                    Class<?> target = (declaring == Class.class) ? Class.class : (Class<?>) receiver;
                    return InvokerHelper.invokeStaticMethod(target, method, args);
                }
            }
        }

        // Closures dispatch through owner/delegate; check the real target, otherwise
        // { -> delegate = System; exit(-1) }() would slip past the whitelist.
        if (receiver instanceof Closure) {
            if (Objects.isNull(InvokerHelper.getMetaClass(receiver).pickMethod(method, argTypes))) {
                for (Object target : closureTargets((Closure<?>) receiver)) {
                    if (Objects.nonNull(InvokerHelper.getMetaClass(target).pickMethod(method, argTypes))) {
                        return checkedCall(target, false, false, method, args);
                    }
                }
            }
        }

        MetaMethod m = InvokerHelper.getMetaClass(receiver).pickMethod(method, argTypes);
        if (Objects.isNull(m)) {
            // methodMissing / invokeMethod / Expando: the real target is unknowable ahead of
            // time, so there is nothing to check. Fail closed.
            throw new SecurityException("Unresolvable call: "
                    + receiver.getClass().getName() + "." + method + formatArgs(argTypes));
        }

        Class<?> declaring = m.getDeclaringClass().getTheClass();
        check(declaring, method, argTypes);
        return InvokerHelper.invokeMethod(receiver, method, args);
    }

    /** Static imports and some AST replacements. */
    public Object checkedStaticCall(Class<?> type, String method, Object[] args) {
        args = fixNull(args);
        check(type, method, MetaClassHelper.convertToTypeArray(args));
        return InvokerHelper.invokeStaticMethod(type, method, args);
    }

    // ----------------------------------------------------------- constructors

    public Object checkedConstructor(Class<?> type, Object[] args) {
        args = fixNull(args);
        if (!isClassAllowed(type)) {
            deny(type, "<init>", MetaClassHelper.convertToTypeArray(args));
        }
        return InvokerHelper.invokeConstructorOf(type, args);
    }

    // ---------------------------------------------------------------- checks

    private void check(Class<?> declaring, String name, Class<?>[] argTypes) {
        if (deniedMethods.contains(name) || !isMethodAllowed(declaring, name)) {
            deny(declaring, name, argTypes);
        }
    }

    /** Whether {@code c} has an entry in the whitelist at all - constructors are gated on
     *  this alone, since a constructor isn't a "method name" the method list could name. */
    private boolean isClassAllowed(Class<?> c) {
        return Objects.nonNull(allowedMethodNames(c));
    }

    /** Whether {@code name} may be called on a receiver declaring it in {@code declaring} -
     *  the class must be whitelisted, and either carry no method-name restriction (empty
     *  set = every method allowed) or explicitly list {@code name}. */
    private boolean isMethodAllowed(Class<?> declaring, String name) {
        Set<String> methods = allowedMethodNames(declaring);
        return Objects.nonNull(methods) && (methods.isEmpty() || methods.contains(name));
    }

    /**
     * The configured method-name set for {@code c} - exact class-name match first, falling
     * back to its directly implemented interfaces (so whitelisting {@code java.util.List}
     * covers any concrete implementation) - or {@code null} if nothing whitelists it.
     */
    private Set<String> allowedMethodNames(Class<?> c) {
        if (Objects.isNull(c)) return null;
        Set<String> direct = allowedMethods.get(c.getName());
        if (Objects.nonNull(direct)) return direct;
        for (Class<?> i : c.getInterfaces()) {
            Set<String> viaInterface = allowedMethods.get(i.getName());
            if (Objects.nonNull(viaInterface)) return viaInterface;
        }
        return null;
    }

    private void deny(Class<?> owner, String name, Class<?>[] argTypes) {
        throw new SecurityException("Rejected: "
                + (Objects.isNull(owner) ? "?" : owner.getName()) + "." + name + formatArgs(argTypes));
    }

    // --------------------------------------------------------------- helpers

    private String formatArgs(Class<?>[] argTypes) {
        StringBuilder sb = new StringBuilder("(");
        for (int i = 0; i < argTypes.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(Objects.isNull(argTypes[i]) ? "null" : argTypes[i].getName());
        }
        return sb.append(')').toString();
    }

    /** Groovy sometimes passes null instead of an array holding a single null. */
    private Object[] fixNull(Object[] args) {
        return ObjectUtils.defaultIfNull(args, new Object[1]);
    }

    private List<Object> closureTargets(Closure<?> c) {
        Object owner = c.getOwner();
        Object delegate = c.getDelegate();
        switch (c.getResolveStrategy()) {
            case Closure.OWNER_FIRST:    return nonNull(owner, delegate);
            case Closure.DELEGATE_FIRST: return nonNull(delegate, owner);
            case Closure.OWNER_ONLY:     return nonNull(owner);
            case Closure.DELEGATE_ONLY:  return nonNull(delegate);
            default:                     return Collections.emptyList(); // TO_SELF
        }
    }

    private List<Object> nonNull(Object a, Object b) {
        if (Objects.isNull(a)) return nonNull(b);
        if (Objects.isNull(b) || a == b) return nonNull(a);
        return Arrays.asList(a, b);
    }

    private List<Object> nonNull(Object a) {
        return Objects.isNull(a) ? Collections.emptyList() : Collections.singletonList(a);
    }

    // ------------------------------------------------------------ bean lifecycle

    /** Wired as this bean's init-method in {@link RuntimeGuardConfiguration} - not a Spring
     *  annotation, so this class stays framework-agnostic. */
    void registerAsActiveGuard() {
        GuardHolder.set(this);
    }

    /** Wired as this bean's destroy-method in {@link RuntimeGuardConfiguration}. */
    void unregisterAsActiveGuard() {
        GuardHolder.clear(this);
    }
}
