package sandbox;

import groovy.lang.Closure;
import groovy.lang.MetaClass;
import groovy.lang.MetaClassImpl;
import groovy.lang.MetaMethod;
import groovy.lang.Script;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import org.apache.commons.lang3.ObjectUtils;
import org.codehaus.groovy.runtime.InvokerHelper;
import org.codehaus.groovy.runtime.MetaClassHelper;

/**
 * Runtime insurance for scripts compiled by {@link InterceptCustomizer}. Framework-agnostic on
 * purpose - it has no Spring annotations of its own. {@link RuntimeGuardConfiguration} builds
 * it as a {@code @Bean} from externalized configuration and wires {@link #registerAsActiveGuard()}/
 * {@link #unregisterAsActiveGuard()} as its init/destroy methods; {@link GuardHolder} is what
 * lets customizer-generated bytecode (which can only bake in compile-time constants, never a
 * live object reference) reach whichever instance that bean-creation produced.
 */
public final class RuntimeGuard {

    /**
     * Class name -> instance method names a script may call on it, checked against the declaring
     * class of the resolved method, not the receiver's static type. Empty set = every method
     * allowed; missing key = nothing allowed. Also what gates {@code checkedConstructor} - a
     * class is constructible iff it has an entry here. {@code java.lang.Object}/{@code
     * java.lang.Class}/{@code groovy.lang.GroovyObject} have no special handling - denied only
     * because nothing keys them by default. {@code groovy.lang.Script} is the one exception,
     * governed by {@link #DENIED_SCRIPT_METHODS} instead.
     */
    private final Map<String, Set<String>> allowedInstanceMethods;

    /**
     * Class name -> instance method names denied on it even though {@link #allowedInstanceMethods}
     * would otherwise allow them - the escape hatch for a method whose declaring class is the same
     * class a deployment has every ordinary reason to whitelist (e.g. "execute" on
     * {@code java.lang.String} - see {@link DefaultAllowlist}), so it can't be closed off by simply
     * leaving that class out of the whitelist. Empty set/missing key = nothing extra denied here;
     * this map never grants anything by itself.
     */
    private final Map<String, Set<String>> deniedInstanceMethods;

    /**
     * Same shape as {@link #allowedInstanceMethods}, checked separately for {@code Foo.bar()}
     * calls that resolve to a genuine static method of {@code Foo} (see the {@code
     * receiver instanceof Class} branch in {@link #checkedCall}) and for static-import calls
     * ({@link #checkedStaticCall}). Independent on purpose - a class can be trusted for its
     * static methods without every instance of it being constructible, or vice versa.
     */
    private final Map<String, Set<String>> allowedStaticMethods;

    /** Static-call counterpart to {@link #deniedInstanceMethods}. */
    private final Map<String, Set<String>> deniedStaticMethods;

    /**
     * {@code groovy.lang.Script} gets a denylist instead of the {@code allowed*Methods} maps
     * above: a script's own {@code def foo(){}} compiles onto a fresh, per-compilation generated
     * class name ({@code Script1}, ...) no whitelist entry could ever name in advance - the
     * whitelist model would block a script from calling its own functions entirely. Safe to allow
     * the rest by default because it's all code {@link InterceptCustomizer} already rewrote at
     * compile time.
     *
     * <ul>
     * <li>{@code evaluate(String|File)} - compiles and runs its argument through a brand new,
     * <b>completely unguarded</b> {@code GroovyShell}. Full sandbox escape, confirmed empirically.
     * <li>{@code getBinding}/{@code setBinding} - read/replace the host app's live {@link
     * groovy.lang.Binding}.
     * <li>{@code run()}/{@code run(File, String[])} - re-runs the whole script body.
     * </ul>
     *
     * <p>Not included: {@code getProperty}/{@code setProperty}/{@code invokeMethod} resolve to
     * {@code groovy.lang.GroovyObject}, not {@code Script} (verified via pickMethod), so the
     * {@code allowed*Methods} maps govern them instead. {@code print}/{@code println}/{@code
     * printf} only write text. {@code hasSetterMethodFor} returns a bare {@code boolean}.
     *
     * <p>Unlike {@link #deniedInstanceMethods}, this one stays a genuine, fixed Java-level
     * denylist rather than something a deployment configures - there is no class name a script's
     * own generated class could ever be addressed by from the outside, so there is nothing for
     * external configuration to key this on in the first place.
     */
    private static final Set<String> DENIED_SCRIPT_METHODS = Set.of("getBinding", "setBinding", "run", "evaluate");

    /** Convenience: the same whitelist governs both instance and static calls, nothing denied. */
    public RuntimeGuard(Map<String, Set<String>> allowedMethods) {
        this(allowedMethods, Map.of(), allowedMethods, Map.of());
    }

    /** Convenience: independent instance/static whitelists, nothing denied. */
    public RuntimeGuard(Map<String, Set<String>> allowedInstanceMethods, Map<String, Set<String>> allowedStaticMethods) {
        this(allowedInstanceMethods, Map.of(), allowedStaticMethods, Map.of());
    }

    public RuntimeGuard(Map<String, Set<String>> allowedInstanceMethods, Map<String, Set<String>> deniedInstanceMethods,
                         Map<String, Set<String>> allowedStaticMethods, Map<String, Set<String>> deniedStaticMethods) {
        this.allowedInstanceMethods = copyOf(allowedInstanceMethods);
        this.deniedInstanceMethods = copyOf(deniedInstanceMethods);
        this.allowedStaticMethods = copyOf(allowedStaticMethods);
        this.deniedStaticMethods = copyOf(deniedStaticMethods);
    }

    private static Map<String, Set<String>> copyOf(Map<String, Set<String>> methods) {
        return methods.entrySet().stream()
                .collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, e -> Set.copyOf(e.getValue())));
    }

    // ------------------------------------------------------------------ methods

    /**
     * @param safe   {@code a?.m()} call
     * @param spread {@code a*.m()} call
     */
    public Object checkedCall(Object receiver, boolean safe, boolean spread,
                               Object methodName, Object[] args) {
        String method = String.valueOf(methodName);
        args = fixNull(args);

        if (safe && Objects.isNull(receiver)) return null;

        if (spread) {
            List<Object> out = new ArrayList<>();
            for (Iterator<?> it = InvokerHelper.asIterator(receiver); it.hasNext(); ) {
                Object o = it.next();
                if (Objects.nonNull(o)) out.add(checkedCall(o, true, false, method, args));
            }
            return out;
        }

        if (Objects.isNull(receiver)) {
            // Groovy treats this as NullObject; nothing dangerous can be reached this way.
            return InvokerHelper.invokeMethod(null, method, args);
        }

        Class<?>[] argTypes = MetaClassHelper.convertToTypeArray(args);

        // "Foo.bar()" compiles to a plain call with a Class receiver. Distinguish a static
        // method on Foo from an instance method of java.lang.Class itself.
        if (receiver instanceof Class) {
            MetaClass mc = InvokerHelper.getMetaClass((Class<?>) receiver);
            if (mc instanceof MetaClassImpl) {
                MetaMethod sm = ((MetaClassImpl) mc).retrieveStaticMethod(method, args);
                if (Objects.nonNull(sm) && sm.isStatic()) {
                    Class<?> declaring = sm.getDeclaringClass().getTheClass();
                    check(declaring, method, argTypes, true);
                    Class<?> target = (declaring == Class.class) ? Class.class : (Class<?>) receiver;
                    return InvokerHelper.invokeStaticMethod(target, method, args);
                }
            }
        }

        // Closures dispatch through owner/delegate; check the real target, otherwise
        // { -> delegate = System; exit(-1) }() would slip past the whitelist.
        if (receiver instanceof Closure) {
            if (Objects.isNull(InvokerHelper.getMetaClass(receiver).pickMethod(method, argTypes))) {
                for (Object target : closureTargets((Closure<?>) receiver)) {
                    if (Objects.nonNull(InvokerHelper.getMetaClass(target).pickMethod(method, argTypes))) {
                        return checkedCall(target, false, false, method, args);
                    }
                }
            }
        }

        MetaMethod m = InvokerHelper.getMetaClass(receiver).pickMethod(method, argTypes);
        if (Objects.isNull(m)) {
            // methodMissing / invokeMethod / Expando: the real target is unknowable ahead of
            // time, so there is nothing to check. Fail closed.
            throw new SecurityException("Unresolvable call: "
                    + receiver.getClass().getName() + "." + method + formatArgs(argTypes));
        }

        Class<?> declaring = m.getDeclaringClass().getTheClass();
        check(declaring, method, argTypes, false);
        return InvokerHelper.invokeMethod(receiver, method, args);
    }

    /** Static imports and some AST replacements. */
    public Object checkedStaticCall(Class<?> type, String method, Object[] args) {
        args = fixNull(args);
        check(type, method, MetaClassHelper.convertToTypeArray(args), true);
        return InvokerHelper.invokeStaticMethod(type, method, args);
    }

    // ----------------------------------------------------------- constructors

    public Object checkedConstructor(Class<?> type, Object[] args) {
        args = fixNull(args);
        if (!isClassAllowed(type)) {
            deny(type, "<init>", MetaClassHelper.convertToTypeArray(args));
        }
        return InvokerHelper.invokeConstructorOf(type, args);
    }

    // ---------------------------------------------------------------- checks

    private void check(Class<?> declaring, String name, Class<?>[] argTypes, boolean isStatic) {
        boolean denied;
        if (Script.class.isAssignableFrom(declaring)) {
            denied = DENIED_SCRIPT_METHODS.contains(name);
        } else if (isStatic) {
            denied = isMethodDenied(deniedStaticMethods, declaring, name) || !isMethodAllowed(allowedStaticMethods, declaring, name);
        } else {
            denied = isMethodDenied(deniedInstanceMethods, declaring, name) || !isMethodAllowed(allowedInstanceMethods, declaring, name);
        }
        if (denied) {
            deny(declaring, name, argTypes);
        }
    }

    /** Whether {@code c} has an instance-method entry in the whitelist at all - constructors are
     *  gated on this alone, since a constructor isn't a "method name" the method list could name. */
    private boolean isClassAllowed(Class<?> c) {
        return Objects.nonNull(namesFor(allowedInstanceMethods, c));
    }

    /** Whether {@code name} may be called on a receiver declaring it in {@code declaring} -
     *  the class must be whitelisted in {@code methods}, and either carry no method-name
     *  restriction (empty set = every method allowed) or explicitly list {@code name}. */
    private boolean isMethodAllowed(Map<String, Set<String>> methods, Class<?> declaring, String name) {
        Set<String> allowed = namesFor(methods, declaring);
        return Objects.nonNull(allowed) && (allowed.isEmpty() || allowed.contains(name));
    }

    /** Whether {@code name} is explicitly denied for {@code declaring} in {@code methods} - unlike
     *  {@link #isMethodAllowed}, an empty/missing set here means nothing extra is denied, not
     *  "deny everything"; this map only ever takes away, never grants. */
    private boolean isMethodDenied(Map<String, Set<String>> methods, Class<?> declaring, String name) {
        Set<String> denied = namesFor(methods, declaring);
        return Objects.nonNull(denied) && denied.contains(name);
    }

    /**
     * The configured method-name set for {@code c} in {@code methods} - exact class-name match
     * first, falling back to its directly implemented interfaces (so whitelisting
     * {@code java.util.List} covers any concrete implementation) - or {@code null} if {@code
     * methods} has no entry for it.
     */
    private Set<String> namesFor(Map<String, Set<String>> methods, Class<?> c) {
        if (Objects.isNull(c)) return null;
        Set<String> direct = methods.get(c.getName());
        if (Objects.nonNull(direct)) return direct;
        for (Class<?> i : c.getInterfaces()) {
            Set<String> viaInterface = methods.get(i.getName());
            if (Objects.nonNull(viaInterface)) return viaInterface;
        }
        return null;
    }

    private void deny(Class<?> owner, String name, Class<?>[] argTypes) {
        throw new SecurityException("Rejected: "
                + (Objects.isNull(owner) ? "?" : owner.getName()) + "." + name + formatArgs(argTypes));
    }

    // --------------------------------------------------------------- helpers

    private String formatArgs(Class<?>[] argTypes) {
        StringBuilder sb = new StringBuilder("(");
        for (int i = 0; i < argTypes.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(Objects.isNull(argTypes[i]) ? "null" : argTypes[i].getName());
        }
        return sb.append(')').toString();
    }

    /** Groovy sometimes passes null instead of an array holding a single null. */
    private Object[] fixNull(Object[] args) {
        return ObjectUtils.defaultIfNull(args, new Object[1]);
    }

    private List<Object> closureTargets(Closure<?> c) {
        Object owner = c.getOwner();
        Object delegate = c.getDelegate();
        return switch (c.getResolveStrategy()) {
            case Closure.OWNER_FIRST -> nonNull(owner, delegate);
            case Closure.DELEGATE_FIRST -> nonNull(delegate, owner);
            case Closure.OWNER_ONLY -> nonNull(owner);
            case Closure.DELEGATE_ONLY -> nonNull(delegate);
// TO_SELF
            default -> Collections.emptyList();
        };
    }

    private List<Object> nonNull(Object a, Object b) {
        if (Objects.isNull(a)) return nonNull(b);
        if (Objects.isNull(b) || a == b) return nonNull(a);
        return Arrays.asList(a, b);
    }

    private List<Object> nonNull(Object a) {
        return Objects.isNull(a) ? Collections.emptyList() : Collections.singletonList(a);
    }

    // ------------------------------------------------------------ bean lifecycle

    /** Wired as this bean's init-method in {@link RuntimeGuardConfiguration} - not a Spring
     *  annotation, so this class stays framework-agnostic. */
    void registerAsActiveGuard() {
        GuardHolder.set(this);
    }

    /** Wired as this bean's destroy-method in {@link RuntimeGuardConfiguration}. */
    void unregisterAsActiveGuard() {
        GuardHolder.clear(this);
    }
}
